language: go
go:
  - "1.11"

services:
  - docker

before_install:
  - make dev_database
  - sleep 30

script:
  - make test
  - make MIGRATE_OS_ARCH=linux-amd64 download_migrate
  - make dev_migrate
  - make test_scrape
