language: go
go:
  - "1.11"

services:
  - docker

before_install:
  - make dev_database
  - sleep 30

script:
  - make test
  - make download_migrate
  - make DATABASE_PASS='' dev_migrate
  - make DATABASE_PASS='' test_scrape
