---

version: '3'
services:
  database:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: imagespy
      MYSQL_ROOT_PASSWORD: root
    image: mysql:8.0.12
    ports:
    - "33306:3306"

  registry:
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    image: registry:2.7.1
    ports:
    - "52854:5000"
    volumes:
    - "./registry/config.yml:/etc/docker/registry/config.yml"
    - "./registry/registry.crt:/etc/tls/registry.crt"
    - "./registry/registry.key:/etc/tls/registry.key"
