version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  tls:
    certificate: /etc/tls/registry.crt
    key: /etc/tls/registry.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
# notifications:
#   endpoints:
#     - name: imagespy
#       disabled: false
#       url: http://127.0.0.1:3001/dockerRegistry/event
#       timeout: 500ms
#       threshold: 5
#       backoff: 5s
#       ignoredmediatypes:
#         - application/octet-stream
